### ISSUE TITLE
Panel: add css variable to control spacing of slotted content

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10119]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add a css variable `--calcite-panel-content-space` to control padding of the content area

### Acceptance Criteria

New CSS var

### Relevant Info

Needed for https://github.com/Esri/calcite-design-system/issues/10095

### Which Component

panel

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

#### Ignore this, using to triple check an automation issue. 
Blocked issues: #10132, #9437894, 879

#10011

**Comment by alisonailea** [comment]
When building new component tokens please follow the component token docs found in the wiki. https://github.com/Esri/calcite-design-system/wiki/component-tokens
Let me know if you have any questions or concerns. Since this is already here, can we use this ticket to add the rest of the Panel component tokens as well?

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.28`
https://codepen.io/Ditwan-Price/pen/NWZYLdP?editors=1100
