### ISSUE TITLE
[Dialog] - content background should be white

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#10809]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The background of the content area is `color.background`.

### Expected Behavior

The background is `color.foreground.1`.

### Reproduction Sample

https://codepen.io/ashetland/pen/WNVqpjw?editors=100

### Reproduction Steps

Compare the reproduction sample of Dialog with [Modal](https://codepen.io/ashetland/pen/ExqBWmE?editors=1000).

### Reproduction Version

v2.13

### Relevant Info

cc @jcfranco @geospatialem 

### Priority impact

impact - p1 - need for current milestone

### Impact

Modal was deprecated in favor of Dialog, but their background colors have different defaults. Correcting this to match Modal will aid migration and will address active feedback from teams.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**Comment by driskull** [comment]
> Modal was deprecated in favor of Dialog, but their background colors have different defaults. Correcting this to match Modal will aid migration and will address active feedback from teams.

Its just using the `calcite-panel`. Why would the panel use a different background color in this instance?

**Comment by macandcheese** [comment]
Prior to the change Modal behaved the same way (default to white, option to change via css property). Similarly to how we have a different default padding in Dialog than we do in Panel. 

This should ease migration from Modal while also allowing Dialog to remain flexible for the increased set of use cases it serves - where both the default (now white) or other values (grey, primarily, but depending on use case other options) can be set via the existing css property.

**Comment by driskull** [comment]
I guess my concern is the inconsistency.

If we have valid use cases for when a panel should have a white background then maybe we should document them by having a prop where users can configure it rather than having to set CSS vars to a specific value.

**Comment by macandcheese** [comment]
This would be a direct response to users asking for this change - honestly I don't have concerns about that level of difference and I don't think we want to limit that level of customization. This is how Modal functioned before, all we are doing is making the new component match that prior default so migrating between components is simpler. 

Making users adjust this via a property seems like an anti-pattern vs. using a css property.

Panel as a standalone component currently does not have many use cases where it shouldn't be the default grey (again, because the primary use case there is slotting in "foreground Blocks") on top of that. Dialog has different use cases, some of which may necessitate an override, but ultimately using the less opinionated white bg makes that a simpler story.

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.33`:

![image](https://github.com/user-attachments/assets/574ce240-51ba-4701-89ff-a1c143ac007f)

**Comment by ellenupp** [comment]
This change is affecting the background of panels slotted into a dialog (background -> foreground-1). Is this intentional? This is a breaking change but it can be mitigated by setting --calcite-dialog-background-color back to --calcite-color-background. It's also a change from the calcite-modal component.

**Comment by driskull** [comment]
I think this was intentional for the panel slotted into dialog internally. @jcfranco should we be more specific with the selector so that any panels used elsewhere in the dialog are not affected? cc @geospatialem @macandcheese

**Comment by geospatialem** [comment]
Reopening to ensure the change only occurs on the internal panel cc @driskull

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.65`, and also including scenarios where slotted `panel`'s content background is unchanged. 🎉

**Comment by ellenupp** [comment]
Thanks, though what if a panel is not directly slotted in the dialog but nested? For example we use panel in shell in dialog and the background color is still white/foreground-1.

**Comment by driskull** [comment]
hmmm that might not work. We would need to update the slotted selector to target any element.

**Comment by driskull** [comment]
Created a new PR to fix your use case.

**Comment by ellenupp** [comment]
Looks good in next.67, thanks!
