### ISSUE TITLE
Bug: l10n formatting issue for calcite-input-date-picker

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-design-system#3531]
### Actual Behavior

incorrect date formatting in multiple locales
1. In LV the date value and the placeholder do not match. The date value once selected shows as 2021.11.4, but the placeholder shows up as DD.MM.YYYY
![LV_date_format](https://user-images.githubusercontent.com/44479773/142259779-3d826ef3-00b0-420b-be62-df67b4fc49b1.png)

2. For KO both the placeholder and date should be displayed as "YYYY-MM-DD" instead of "YYYY.MM.DD."
![KO_date_format](https://user-images.githubusercontent.com/44479773/142261997-c73aec69-bc3f-4888-963f-b0ce29fda8fd.png)

3. For HE, both the placeholder and date should be displayed as "YYYY/MM/DD" (read from right to left).
4. For DA, both the placeholder and date should be displayed as "DD-MM-YYYY" instead of "DD.MM.YYYY".

### Expected Behavior

1. For LV, The date value format should be changed to DD.MM.YYYY similar to how the placeholder already is.
2. For KO both the placeholder and date should be displayed as "YYYY-MM-DD" instead of "YYYY.MM.DD."
3. For HE, both the placeholder and date should be displayed as "YYYY/MM/DD" (read from right to left).
4. For DA, both the placeholder and date should be displayed as "DD-MM-YYYY" instead of "DD.MM.YYYY".

### Reproduction Steps and Sample

(https://codepen.io/rpanichakit/pen/dyzwBEV)

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

**Comment by BlakeStearman** [comment]
@benelan for triaging.

@paulcpederson may be able to help.

**Comment by fendiaoxiaoshuazi** [comment]
1. For BS, the date value format should be changed to DD.MM.YYYY. similar to how the placeholder already is.
2. For ZH-HK, both the placeholder and date should be displayed as "DD/MM/YYYY" instead of "YYYY/MM/DD"

**Comment by Olga8614** [comment]
We verified this defect on AGOL 10.2 devext site (5/13/2022) in LV language with Safari/Chrome/Edge(Chromium)/FF browsers.
The hint message is displayed as "DD.MM.YYYY" as expected.
But Format of selected date is displayed as "DD.MM.YYYY." rather than "DD.MM.YYYY" (That is, redundant point is displayed at the end of date) on left filters pane under Gallery/Groups/Content/Organization tab.
So this defect is partly fixed. Thanks!
![image](https://user-images.githubusercontent.com/29614798/168405054-76d2ff30-a511-449b-b243-fa169c2b395c.png)

**Comment by Olga8614** [comment]
We verified this defect on AGOL 10.2 devext site (5/16/2022) in HE/da-DK/ko-KR/CA language with Safari/Chrome/Edge(Chromium)/FF browsers.
Date separatpr is displayed well in Start/End textbox under Gallery/Groups/Content/Organization tab.
For HE, both hint message and date is displayed as "DD.MM.YYYY" (read from right to left).
For ko-KR, both hint message and date is displayed as "YYYY.MM.DD" as expected.
For da-DK, both hint message and date is displayed as "DD.MM.YYYY"as expected.
For CA, both hint message and date is displayed as "DD/MM/YYYY" as expected. So this defect is fixed. Thanks!

**Comment by Olga8614** [comment]
This behavior also occurs on it-CH language on Search/Gallery/Group/Content/Organization pages, please refer to the screenshot "9213_it-CH.jpg".
![image](https://user-images.githubusercontent.com/29614798/168933358-18032b8e-77b5-43d3-9108-7ae8b47898a8.png)

**Comment by Olga8614** [comment]
We verified this defect on ArcGIS Online 10.3 devext site (8/29/2022) in LV/it-CH languages with Safari/Chrome/Edge Chromium/FF browsers.
The hint message is displayed as "DD.MM.YYYY" in LV/it-CH languages as expected.
But Format of selected date is displayed as "DD.MM.YYYY." rather than "DD.MM.YYYY" in LV language (That is, redundant point is displayed at the end of date) on left filters pane under Gallery/Groups/Content/Organization tab.
And Format of selected date is displayed as "DD/MM/YYYY" rather than "DD.MM.YYYY" in it-CH language on left filters pane under Gallery/Groups/Content/Organization tab.

The result is same as the above comments of 8/25/2022.
So this defect is not fixed. Thanks!

**Comment by geospatialem** [comment]
Since the backend of `input-date-picker` in the last year, it looks like all locales have been mitigated with the exception of Hebrew (`he`) as indicated with `2.1.0` in [this updated Codepen](https://codepen.io/geospatialem/pen/wvOzZOz), where the expected format is `"YYYY/MM/DD"`, but it is depicted as `"DD.MM.YYYY"`.

@annierm18 Can you confirm if the expected date format for Hebrew is `"YYYY/MM/DD"` for the following:

```html
 <calcite-input-date-picker lang="he"></calcite-input-date-picker>
```

**Comment by annierm18** [comment]
@geospatialem I looked into this issue and found that the current date format for "he" is correct and does not need to be changed. This is based on the short date pattern for "he" in CLDR & ICU as well as information from a distributor.

cc: @Olga8614

**Comment by geospatialem** [comment]
Thanks for the expertise and looking into this, @annierm18! Per [Aine's comment above](https://github.com/Esri/calcite-design-system/issues/3531#issuecomment-2027639259), closing the above request as the component is in alignment with CLDR and ICU.
