### ISSUE TITLE
Setting tabindex="-1" on calcite-button does not work

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-design-system#4970]
### Actual Behavior

When I set tabindex="-1" on a calcite-button I would expect to not be able to give it focus by tabbing to that element.

### Expected Behavior

calcite-buttons with tab-index="-1" gets focus when tabbing.

### Reproduction Sample

https://codepen.io/mjuniper/pen/MWVpLdj?editors=1000

### Reproduction Steps

1. visit https://codepen.io/mjuniper/pen/MWVpLdj?editors=1000
2. get focus into the preview pane
3. tab sequentially

observe that both calcite-buttons get focus (one has tabindex="-1" and one does not.

### Reproduction Version

beta.83

**Comment by driskull** [comment]
@jcfranco I think this is an issue with the `updateHostInteraction` utility function. Its removing tabindex set by the user.

**Comment by jcfranco** [comment]
@driskull We could look into having the util check for any user-set `tabindex` before taking control, but there could be cases where we still need to override it at runtime (e.g., to prevent tabbing into children).

@mjuniper May I ask what your use case is? For context, all interactive components control the component/host element's `tabindex` to support the `disabled` state.

**Comment by driskull** [comment]
> but there could be cases where we still need to override it at runtime (e.g., to prevent tabbing into children).

Yeah thats the tricky part. It would need to store the user defined value and set it back when necessary.

**Comment by driskull** [comment]
> For context, all interactive components control the component/host element's tabindex to support the disabled state.

I do think the use case is reasonable though. A user would expect their defined tabindex to be honored. I think it falls into the category of not messing with host attributes/classes.

**Comment by jcfranco** [comment]
> @mjuniper May I ask what your use case is? For context, all interactive components control the component/host element's tabindex to support the disabled state.

Friendly ping. 😄

---

Side note: it looks like [support for `inert` is getting there](https://caniuse.com/?search=inert), at least from a `last 2 versions` perspective. Once it's widely supported, we'll definitely refactor our interactive component pattern and we would no longer need to mess w/ the host's tab index.

If this is a showstopper, we could look at introducing an internal component solely to prevent interaction with its content. @driskull Most, if not all, of our components have a root container, right?

**Comment by driskull** [comment]
@jcfranco correct. Most but not all.

**Comment by geospatialem** [comment]
Blocked by Firefox, will investigate once this can be adopted across browsers.

**Comment by jcfranco** [comment]
@driskull Let's sync up on a potential approach and timeline for this. Without `inert`, this could be risky for 1.0.0.

**Comment by paulcpederson** [comment]
Just ran into this. The use case is when you're managing focus for a role like `grid` and you want to have arrow keys cycle focus rather than tab. This bug makes it impossible to prevent focus of a calcite button (or calcite action).

**Comment by paulcpederson** [comment]
@geospatialem our team would like to  move this out of the freezer and get it on a sprint.

**Comment by jcfranco** [comment]
@paulcpederson Perfect timing. I have an idea to fix the remaining failing test from https://github.com/Esri/calcite-design-system/pull/7557 that might help tackle this.

Could you provide details on impact/severity and timeline for this?

> Also, you won't be able to just rely on inert. The inert attribute prevents focus and clicks. In a grid role, that's not what you're trying to achieve. You want the user to be able to click the button anytime, but you want to manage when the button will receive focus.

Also can you you share more about this scenario? Our current usage of `tabindex="-1"` is to support consistent `disabled` behavior across components. We need to set the attribute on the host to prevent tabbing and we also use JS and CSS to handle pointer interaction.

**Comment by driskull** [comment]
@jcfranco I think the problem is this part: by default, `hostIsTabbable` is false and this function is called every time the component is rendered so its always removing the `tabindex` on the `host`. So you can't set `tabindex="-1"` on a component and have it stay there meaning it will always get focus unless disabled.
https://github.com/Esri/calcite-design-system/blob/41d7d9714477ba3f7a4b3e01969d24ffaf91e461/packages/calcite-components/src/utils/interactive.ts#L112-L120

**Comment by paulcpederson** [comment]
> Could you provide details on impact/severity and timeline for this?

I think I can work around by not using a calcite button, but would be nice to not have to reinvent the wheel. This is for a project going out 2024 R01, but needs to be done end of R03 for testing, etc.

> Also can you you share more about this scenario? 

Consider something like the example on the aria grid role page on mdn https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/grid_role

<img width="306" alt="Screenshot 2023-08-29 at 1 06 26 PM" src="https://github.com/Esri/calcite-design-system/assets/1031758/df56b56c-03b8-4aa3-afde-fa32c0a36ac3">

The desired keyboard interaction is that you tab to the grid, then you use arrow keys to move around the grid, and then you hit tab and you move past the grid. The generally understood way to accomplish a keyboard interaction like this is to make sure focusable elements have `tabindex=-1` when they are not the active grid cell (and tabindex 0 when they are). 

If I was to add calcite-buttons to that example, tab would just go to the next button rather than out of the table completely. I have no recourse or tool I can use to prevent the calcite button from receiving focus. If I use `inert` mouse users will not be able to click the button. There has to be a way for me as an app author to disable just keyboard focus of the button while leaving it available to mouse users.

Inert will also remove the component from the accessibility tree entirely. Meaning in situations where apps are setting a button as disabled until a particular option is filled out if you use inert, screen readers will have no idea there is a disabled button there

**Comment by jcfranco** [comment]
@paulcpederson @driskull Thanks for the info. 

I should've shared more details on what I was thinking for the fix. 😅 We could introduce an internal 'focus guard' container component that itself would be used to set `tabindex="-1"`, or `inert`, when disabling a component. This would free up the main component's `tabindex` and allow a roving `tabindex` pattern like for the grid case above.

**Comment by paulcpederson** [comment]
ooooooooh, ok yeah that makes sense sorry to derail 😬

**Comment by jcfranco** [comment]
No worries at all. 😄

**Comment by jcfranco** [comment]
@geospatialem @brittneytewks Triaged this one. We'll need a milestone.

**Comment by jcfranco** [comment]
[Belated spike update] I think we can get this done in December/January and it might even be an estimate 3. I have a [prototype](https://github.com/Esri/calcite-design-system/pull/8166) with promising results. The following components  would need to be updated once E2E testing looks ✅:

* [ ] `action.tsx`
* [ ] `block.tsx`
* [x] `button.tsx`
* [ ] `checkbox.tsx`
* [ ] `chip-group.tsx`
* [ ] `chip.tsx`
* [x] `color-picker.tsx`
* [ ] `combobox-item.tsx`
* [ ] `combobox.tsx`
* [x] `date-picker-day.tsx`
* [ ] `dropdown.tsx`
* [ ] `fab.tsx`
* [ ] `filter.tsx`
* [ ] `flow-item.tsx`
* [ ] `inline-editable.tsx`
* [ ] `input-date-picker.tsx`
* [ ] `input-number.tsx`
* [ ] `input-text.tsx`
* [ ] `input-time-picker.tsx`
* [ ] `input-time-zone.tsx`
* [ ] `input.tsx`
* [ ] `link.tsx`
* [ ] `list-item-group.tsx`
* [ ] `list-item.tsx`
* [ ] `list.tsx`
* [ ] `panel.tsx`
* [x] `pick-list-item.tsx`
* [ ] `pick-list.tsx`
* [ ] `radio-button.tsx`
* [ ] `rating.tsx`
* [ ] `segmented-control.tsx`
* [ ] `select.tsx`
* [ ] `slider.tsx`
* [ ] `sortable-list.tsx`
* [ ] `split-button.tsx`
* [ ] `stepper-item.tsx`
* [ ] `switch.tsx`
* [x] `tab-title.tsx`
* [ ] `table-cell.tsx`
* [ ] `table-row.tsx`
* [ ] `text-area.tsx`
* [ ] `tile-select-group.tsx`
* [ ] `tile-select.tsx`
* [ ] `tile.tsx`
* [ ] `tree-item.tsx`
* [x] `value-list-item.tsx`
* [ ] `value-list.tsx`

**Comment by DitwanP** [comment]
🧁 Verified locally on `main`
