### ISSUE TITLE
Combobox item not finding parent's scale

### ISSUE THREAD

**Issue by ReidPritchard** [Esri/calcite-design-system#5276]
### Actual Behavior

Combobox items use a closest call in their `connectedCallback` method to find their scale, but on initial load their `combobox` parent does not have their properties set in the DOM. This means the combobox-item falls back to a scale of 'm'. This then leads to odd UI when adding or removing items dynamically since the new items are properly scaled but the old items are not.

This is not a problem if closest is called in any other lifecycle method.

### Expected Behavior

Combobox-item should find the appropriate scale based on it's parent.

**Workaround**: 
Right now you can set the "scale" property on the combobox-item directly since the closest call will check the element itself before looking to it's parent.

An easy solution would just be exposing the scale prop on combobox-item. I also believe, calling closest in `componentWillLoad` would also solve the issue, maybe with a check if scale is currently undefined.

### Reproduction Sample

https://github.com/ReidPritchard/stencil-lifecycle-repro

### Reproduction Steps

1. Clone the repo
2. run `yarn && yarn start`
3. open the console to see the slotted `connectedCallback` being called before the parent. Also notice `closest` finds the property when called from any other lifecycle method.

### Reproduction Version

beta.93

**Comment by driskull** [comment]
For this one, we shouldn't be looking up the parent's scale. We should have the parent update the children's scale.

**Comment by geospatialem** [comment]
This issue will require a refactor and will be prioritized after the 1.0 release next month.

**Comment by jcfranco** [comment]
I looked into this and found it doesn't seem valid for the following reasons:

1. Child components no longer look up the ancestry for scale and similar props (see [related PRs](https://github.com/Esri/calcite-design-system/pulls?q=is%3Apr+sort%3Aupdated-desc+getelementprop+is%3Aclosed)).
2. Parent/child components are wrapped in separate components, which is not a pattern we recommend.
3. Lifecycle note under repro steps is expected per [Stencil documentation](https://stenciljs.com/docs/component-lifecycle#lifecycle-hierarchy).

LMK if there's an updated use case we can look into. Otherwise, we will proceed to close this.

**Comment by jcfranco** [comment]
I'm going to go ahead and close this. Please feel free to reopen if there's an updated repro case.
