### ISSUE TITLE
Docs: add code examples for common JavaScript workflows

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-design-system#5836]
### Description

We should create JavaScript/TypeScript snippets for common workflows. I think we should either add them to [`calcite-components-examples`](https://github.com/Esri/calcite-components-examples) or the [Calcite Documentation](https://developers.arcgis.com/calcite-design-system/), but I'm open to other suggestions (maybe the component readmes?). 

An example is the JavaScript code required to drill in/out using `calcite-flow`. We should provide code for vanilla JS, as well as any output targets we end up providing (currently React).

If we add them to the Calcite Documentation, it may be benefical to provide full codepen/codesandbox examples along with an explanation.

### Which Component

- [x] Flow and Flow Item - Drill in/out
    - [x] Doc site
    - [x] calcite-components-examples repo
- [x] Slider - histogram
    - [x] Doc site
    - [x] calcite-components-examples repo

### Resources

We've recieved various feedback that JavaScript/React examples would be helpful, including this thread:
https://community.esri.com/t5/calcite-design-system-questions/managing-calcite-panels-within-calcite-flow-in/m-p/1235115

**Comment by geospatialem** [comment]
Updated the context for inclusion on the doc site and calcite-components-example repo - reassigned to June's milestone.

**Comment by macandcheese** [comment]
I think this could be wrapped up in a larger effort to move all usage examples to this repo. Currently, the doc site authors in MDX because of how tightly we integrate with Gatsby / GraphQL for the rest of our content. But it also allows us to add fenced css and js examples.

Some places we do this:
- Examples where we toggle a Modal / Sheet with a button
- Adding multiple Alert to a queue with a button
- Using Flow to programmatically create new Flow Item and navigate to them
- In our more "pattern-y" examples - to handle opening and closing Action Bar / Shell Panel / Panel.

Ideally all of this can live here, not in the documentation repo (which, as long as we deploy through the Developer site Gatsby infrastructure, will always be separate). Would be great to sync up on this over next few months. 

The end goal is to make that Gatsby component into a standalone web component package that could work for any Stencil web component project that uses a JSDoc output file. But, in the interim, we could still look to source the content from a single source of truth here.

**Comment by DitwanP** [comment]
For verification of the cc examples repo. cc @geospatialem
- Make sure you have latest changes locally on `main` for the `calcite-components-examples` repo. 
- Navigate to `common-patterns`
- Run `npm install` and then `npm start`

**Comment by geospatialem** [comment]
Verified the following on 12/27/23:
1. Developer site: both `flow` and `slider` examples with histograms on the [developer site](https://developers.arcgis.com/calcite-design-system/components/slider/) 🎚️ 🎐 
2. Examples repo: the `main` branch within `common-patterns` 📑
