### ISSUE TITLE
Popover support for trigger events such as click (`Enter`) and hover (`:focus`)

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6298]
### Description
The ArcGIS Urban team needs the following kinds of non-modal components (using tooltips/popovers):

- [x] Displays on hover (and on focus for keyboard accessibility compliance) and contains a simple text → `tooltip`
- [x] Displays on click (and on Enter key press, for accessibility compliance as well) contains more complex content such as links, Checkbox, Input Date Picker, Button etc. → `popover`
- [ ] Displays on `:hover` (and `:focus`) only and contains more complex content → `popover` (refer to the acceptance criteria below)

### Acceptance Criteria
Open popover with different types of trigger events like in [`type` in `dropdown`](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-type) with the following options:

- Click and the Enter key or
- Hover and when focused
    - If this option is selected there should be a way that the click and enter key events do not toggle the component's open prop.

#### Use case screenshots:
![image](https://user-images.githubusercontent.com/5023024/213204733-364fe1ca-2a03-4180-a003-5ba94ae2fb32.png)

![image](https://github.com/Esri/calcite-components/assets/5023024/f6a68d2a-998d-4ac9-8c49-74156419b4d7)

### Relevant Info
Would be similar in functionality to the [`type` in Dropdown](https://developers.arcgis.com/calcite-design-system/components/dropdown/#component-api-properties-type).

Accessibility and documentation around its accessibility will need to be considered to ensure the popover contents are provided to assistive technologies. In the [following example] the popover contents are only provided to assistive technologies when in focus (not while hovered, which could be provided via an `aria-live` prop.

### Which Component
`popover`

### Example Use Case
The following [Codepen serves as a hacky example](https://codepen.io/geospatialem/pen/MWBEvMX) but disables the focus trap using the `focusTrapDisabled` property, which is the expected behavior for assistive technologies. It also still includes the ability to `open` the component with a click or `Enter` key event.

### Esri team
ArcGIS Urban

**Comment by Anastasiia-Boleiko** [comment]
Hello,

Could you please clarify what is the approximate time for having this feature in the Calcite release? 

Thank you.

**Comment by geospatialem** [comment]
> Hello,
> 
> Could you please clarify what is the approximate time for having this feature in the Calcite release?
> 
> Thank you.

Thanks for re-pinging this issue, @Anastasiia-Boleiko. It looks like the description was removed with one of our automations so this one got lost in the shuttle. We'll be taking a look/sign-off on design in the near future.

**Comment by geospatialem** [comment]
Check into the autofocus on hover with dropdown for accessibility considerations.

**Comment by geospatialem** [comment]
The functionality looks okay when animations are disabled (Windows) or reduced (Mac) when coupled with other elements on the page and focus shifts on hover. 

There do not appear to be any accessibility concerns in scoping with the request.

**Comment by driskull** [comment]
> Check into the autofocus on hover with dropdown for accessibility considerations.

Yeah that might be weird if a dialog role (popover) is automatically opened and focused when a reference element is hovered.

**Comment by driskull** [comment]
I'm not sure this is a valid use case. When hovering or focusing a reference element and having the popover automatically open it would automatically focus and trap on the popover. I don't think that is a good experience when someone is tabbing through the document to have their focus automatically taken away.

**Comment by Anastasiia-Boleiko** [comment]
> I'm not sure this is a valid use case. 

@driskull I understand your concerns. However, have you considered whether the following user interface is a valid use case?
![image](https://github.com/Esri/calcite-design-system/assets/119309703/7c1d41bb-9899-4490-8ec1-11b47375458d)
When user focuses a tool button:
 - a popover with help info and a link is displayed
 - the focus is moved to the More how link (the first component in the popover)
 - and there is no focus trap. 
 Under the focus trap, in this case, I mean allowing a user to use "Tab" key to navigate to the next interactive element, which is the next tool button in this specific case.

P.s.: Click does not work in this case since it activates the tool.  

Also, in case, a popover has auto-close property, I would consider having no trap. This means that when the popover is opened and there are no interactive elements inside, or the user has focused the last interactive element within the popover, pressing "Tab" moves the focus to the next interactive element outside of the popover. In this [example](https://codepen.io/anastasiia-zrh/pen/qBLOYYV?editors=100), when the popover is open, the user should be able to move on to the next interactive element, such as "Button 2," without having to close the popover. What is your opinion on this?

**Comment by driskull** [comment]
I'm not sure if thats a valid use case, its hard to say since that comparison is adobe photoshop and not a web browser.

> Also, in case, a popover has auto-close property, I would consider having no trap. This means that when the popover is opened and there are no interactive elements inside, or the user has focused the last interactive element within the popover, pressing "Tab" moves the focus to the next interactive element outside of the popover.

I think in this case a tooltip would work, right?

**Comment by geospatialem** [comment]
Reassigning to November as a research spike effort for additional efforts.

**Comment by driskull** [comment]
I think we could enhance the tooltip to have arrow key support to select focusable elements. We would just not promote this approach because there are currently no a11y guidelines for this. However, it would work for both mouse and keyboard users if we do this. We could still keep our doc guidelines that no interactive elements should be in a tooltip but if they are we can make them work. Would this work?

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.6`
https://codepen.io/Ditwan-Price/pen/QWXgrJX?editors=100
