### ISSUE TITLE
Allow for Segmented Control to Display Icon Only

### ISSUE THREAD

**Issue by apfister** [Esri/calcite-design-system#6413]
### Description

Allow for the Segmented Control (and item?) display an icon only, without having to specify text.

In the image below, I'd like only the icons to be displayed:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/5233042/216201554-f462bb36-4dee-4e35-9e46-04d8af4ae8c2.png">

### Acceptance Criteria

maybe `iconOnly` as a property? or just display only the icon if that's the only thing specified.

### Which Component

Segmented Control / Segmented Control Item

### Esri team

N/A

**Comment by ashetland** [comment]
This one is on my list as well. Thanks for filing this, @apfister.

**Comment by jgrayson-apl** [comment]
+1
We need a simple 'multiple options' toggle and a segmented-control would have been a nice option as we wouldn't need to manage having only one option selected and reacting to just one selection event.  Having multiple calcite-actions works, but its a lot of unnecessary work if the segmented-control had an iconOnly option.

![image](https://user-images.githubusercontent.com/5324720/223564036-81dfe947-270e-43ab-a3e1-5b03065c9225.png)

**Comment by macandcheese** [comment]
Would be a nice add. We can probably do as we do with button, etc., and adjust padding when only an icon property is provided.

**Comment by geospatialem** [comment]
This use case also surfaced in a [Community thread](https://github.com/Esri/calcite-components/issues/6413) on 5/18, in which the use case is to display icons without text in the component.

**Comment by tsellste** [comment]
Here is my use case.  The icons would be sufficient and use much less horizontal space.
<img width="244" alt="image" src="https://github.com/Esri/calcite-components/assets/3936265/193f0f13-04ba-4a9d-99ad-0e9c6255bbfc">

**Comment by ashetland** [comment]
[Figma file](https://www.figma.com/file/6crYuljrJ6dLrWoZrZzKhW/Segmented-Control---Icon-Only-%5B6413%5D?type=design&node-id=401-2860&mode=dev) ready for this update.

**Comment by macandcheese** [comment]
To achieve this, we'll need to prevent using `value` as the displayed text when there is no slotted text, and update the padding for icon-start/end to center visually within the container. Probably a similar `hasText` internal state like Button has to determine a conditionally applied class, etc.

**Comment by jcfranco** [comment]
@macandcheese Added a `text-disabled` property to opt-into this behavior as using the `value` as a label is a feature and is also used in other components (e.g., `calcite-option`).

While working on this, I also found using icons instead of text for the label could be a potential workaround (see [codepen](https://codepen.io/jcfranco/pen/bGybXmZ)).

**Comment by ashetland** [comment]
Since it has icon-start/end, is the workaround workflow possibly confusing? I suppose `text-disabled` might also be confusing because there's no `text` prop like Action?

**Comment by jcfranco** [comment]
> Since it has icon-start/end, is the workaround workflow possibly confusing? 

How do you mean?

> I suppose text-disabled might also be confusing because there's no text prop like Action?

We already use `textDisabled` w/o a matching `text` prop in [`navigation-user`](https://github.com/Esri/calcite-design-system/blob/f1ff5e1acd0e802f6c5b635a77dedf8138d7e753/packages/calcite-components/src/components/navigation-user/navigation-user.tsx#L33-L34).

> I believe the [idea](https://www.figma.com/design/6crYuljrJ6dLrWoZrZzKhW/Segmented-Control---Icon-Only-%5B6413%5D?node-id=441-15358&t=crTc3ZABfLCh9Kf2-11) was to make value required, but if no text is in the default slot and an icon prop is used, we'd get the same end result.

OK, so I tracked down the behavior I called out in my earlier comment and it looks like using `value` as the fallback label is [intentional](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/segmented-control-item/segmented-control-item.e2e.ts#L38-L46), but there is no explicit spec for it in the [original issue](https://github.com/Esri/calcite-design-system/issues/5), [PR](https://github.com/Esri/calcite-design-system/pull/72) nor [documentation](https://developers.arcgis.com/calcite-design-system/components/segmented-control/). It's sort of an outlier and also [breaks if there's any whitespace](https://codepen.io/jcfranco/pen/XWwWGEy?editors=1000). Also, `value` might not be the best option for a user-friendly label (e.g., casing, localization). For these reasons, I think it's safe to drop to simplify the behavior w/o it constituting a breaking change.

**Comment by jcfranco** [comment]
Thanks for the catch, @ashetland! I'll make the appropriate adjustments.

**Comment by DitwanP** [comment]
🍡 Verified locally on `main`
