### ISSUE TITLE
[Alert] Responsive layout

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6673]
### Description

Mobile responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

- [ ] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [ ] 2. Components need to be designed for the following breakpoints:
    - [ ] Small (s), `476px`
    - [ ] Medium (m), `768px`
    - [ ] Large (l), `1152px`
    - [ ] Extra larger (xl), `1440px`

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`alert`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by SkyeSeitz** [comment]
Update from team discussion today:
@rmstinson presented Alert footer iterations for smaller screen sizes and mobile devices, which we will put on hold to first finalize the [Alert stacking enhancement](https://github.com/Esri/calcite-components/issues/2835) currently in progress.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/29716057/232863479-3c9981be-2fa2-4ad7-adea-3a4c1f8d8cf0.png">

**Comment by rmstinson** [comment]
It looks like I can't assign myself to this issue @SkyeSeitz but at least I can comment now!

**Comment by geospatialem** [comment]
Just added 'ya @rmstinson 👍🏻

**Comment by rmstinson** [comment]
Compact Alerts have been built - they're intended for use at a width of 767px and lower. 

Building them also presented an opportunity to streamline the regular Alert component - currently we have a variant for autodismiss, and a variant for default. However, it's possible to build the component with a show/hide boolean for the Progress component, so that we can have a configuration option for autodismiss, and cut the number of variants in the component in half.

Take a look here: https://www.figma.com/file/eradSav1w0c4viNljdROKk/Alert---responsive-design-%5B6673%5D?type=design&node-id=517%3A12655&mode=design&t=eM0Y3CNz80p4B0wH-1

![Screenshot 2023-06-28 at 4 01 30 PM](https://github.com/Esri/calcite-components/assets/12650705/51fbeb2c-f16e-4de3-9aaa-91e9670423ab)

If we're happy with this approach I can change the rest of the Alerts as well. This might have ramifications for the Notice component as well @ashetland

**Comment by SkyeSeitz** [comment]
Thanks, @rmstinson. Prototype and specs marked as [ Ready for Dev](https://www.figma.com/file/eradSav1w0c4viNljdROKk/Alert---responsive-design-%5B6673%5D?type=design&node-id=519-12408&mode=dev).

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.16` for all cases, with the exception of `"actions-end"` slots where `textEnabled` is `true` and `text` exceeds the component's width. 

Opened https://github.com/Esri/calcite-design-system/issues/7921 to mitigate the latter.
