### ISSUE TITLE
Calcite Input Number not showing value

### ISSUE THREAD

**Issue by previnWong** [Esri/calcite-design-system#7014]
### Actual Behavior

I have a variable assigned to the value parameter (10).  On load, it shows a blank.  but if you press the arrow to increase/decrease, it either goes 9 or 11 so it respects the default value.
![image](https://github.com/Esri/calcite-components/assets/11183838/f05852fd-0d92-4cba-899d-92a9cc90fd24)
![image](https://github.com/Esri/calcite-components/assets/11183838/b315f0e3-8d01-4e08-b380-b5b8764f266f)
![image](https://github.com/Esri/calcite-components/assets/11183838/8d608ecd-8d34-4bdc-bae3-05aebdd2a4d9)

### Expected Behavior

Once "result area" is toggled, the Input Number should show 10 in the text area.

### Reproduction Sample

~https://codepen.io/pwongEsri/pen/mdzvBeK?editors=1000~
https://codepen.io/maxpatiiuk/pen/bGOxqaZ?editors=1000

### Reproduction Steps

~Repo app~
~https://codepen.io/pwongEsri/pen/mdzvBeK?editors=1000~
~please ask for login~
 
~1) select "downstream" trace, click any asset on the map, and run~
~2) Enabled the "result area" toggle, notice input number is blank.~

Note, the issue only happens when calcite-input-number is rendered by Maquette via a JS API widget, rather than directly in the browser.

### Reproduction Version

JS SDK 4.27

### Priority impact

p3 - want for upcoming milestone

### Esri team

ArcGIS Solutions

**Comment by jcfranco** [comment]
@previnWong I'm having a hard time reproducing that issue in isolation. Is there any additional info you could share about the issue (e.g., the state of the component before its value is updated)?

**Comment by previnWong** [comment]
When first rendered, the variable storing the value is already set.
![image](https://github.com/Esri/calcite-components/assets/11183838/2f0cf2fd-9a40-4e06-98b1-0baff2d8afe5)

Input Number is in shadow root
![image](https://github.com/Esri/calcite-components/assets/11183838/b243aee7-d178-4e5d-b6de-62fa3e4e4160)

**Comment by maxxxxxdlp** [comment]
I have the same problem. If you are still having issues reproducing this, I can provide a codepen sample

**Comment by JonUihlein** [comment]
Bumping; I am able to reproduce a similar issue with `CalciteInputDatePicker` using the `value` property, whereas using `valueAsDate` works fine. Maybe tangentially related since the date picker is using a Calcite Input under the hood?

**Comment by geospatialem** [comment]
@maxxxxxdlp + @JonUihlein thanks for pinging this issue. If either of you are able to provide a Codepen that'd be helpful for us troubleshooting to identify a solution, perhaps with `input-number` and also `input-date-picker` present for comparison?

**Comment by maxxxxxdlp** [comment]
Hi. I created this CodePen that reproduces the issue: https://codepen.io/maxpatiiuk/pen/bGOxqaZ?editors=1000

Note, the issue only happens when calcite-input-number is rendered by Maquette via a JS API widget, rather than directly in the browser.

Is this sufficient for you to investigate the cause, or do you need me to explore what specifically in Maquette/JS API rendering pipeline could be interfering with Calcite?

**Comment by rslibed** [comment]
This impacts instant apps

**Comment by kellyhutchins** [comment]
@jcfranco  this affects our config panel. We are wondering if there will be a fix for the next calcite release? Or should we just swtich to non-calcite inputs for this release.

**Comment by kellyhutchins** [comment]
Thanks @maxxxxxdlp!

**Comment by jcfranco** [comment]
Apologies for the delayed reply. It looks like this issue only affects the `components` output target and seems to be caused by the component initializing its value when [attached to the DOM](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-number/input-number.tsx#L436), and watchers not reacting to Maquette setting the component's [value right after attachment](https://github.com/AFASSoftware/maquette/blob/59b4914d23743ed4f9de748ffbb345e5ca7933bc/src/projection.ts#L342). The `value` watcher won't get triggered because the prop is updated before the component's first load/render (i.e., [before watchers are initialized](https://stenciljs.com/docs/reactive-data#:~:text=The%20%40Watch()%20decorator%20does%20not%20fire%20when%20a%20component%20initially%20loads.)).

Thank you so much for the updated repro cases! 🎉

**Comment by jcfranco** [comment]
[Here](https://stackblitz.com/edit/github-ojdkyo?file=src%2Fmain.js,public%2Findex.html)'s a stackblitz to verify this with the `components` output target. cc @geospatialem @DitwanP

**Comment by geospatialem** [comment]
Verified in `2.7.0-next.16` with the [template shared by Franco](https://github.com/Esri/calcite-design-system/issues/7014#issuecomment-2021163695), where the default value of `10` is displayed on initialization. 🎉
