### ISSUE TITLE
[Action / Pad / Group] Extra border when using Action Pad / Group / Action in Grid layout

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#7380]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using Action Pad in "Grid" layout, along with an Action Group and set of Actions - there is 1px extra at the left and right edges.

<img width="346" alt="Screenshot 2023-07-26 at 9 56 51 AM" src="https://github.com/Esri/calcite-design-system/assets/4733155/8ee01e00-e590-4aa8-a3f4-fefa787ef5d3">

### Expected Behavior

I'd expect the Action Group to extend fully to the edges of the Pad and not have 1px transparent border.

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/mdQzRXo?editors=1000

### Reproduction Steps

1. Open Codepen

### Reproduction Version

Latest

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by maxxxxxdlp** [comment]
Besides 1px gap, there is also a 1px padding (only if layout is grid):

![Screenshot 2023-07-26 at 14 38 09](https://github.com/Esri/calcite-design-system/assets/40512816/c28e172c-0ab3-441e-aecd-70ac3a225233)

Fortunately, it's easy enough to override with css

**Comment by SkyeSeitz** [comment]
I agree Action Group should extend fully to the edges of the Pad without 1px transparent border. However, I could see the dividing borders between Actions remaining on `layout=grid` to provide some visual structure when there are both rows and columns.

**Comment by macandcheese** [comment]
I think that's a good medium - the visual border isn't needed with a single row Action Pad or Action Group, but when there are multiple rows of Actions in a `layout="grid"` - I agree having the border there is nice. I will update OP.

**Comment by maxxxxxdlp** [comment]
This issue wasn't a big priority before because I could overwrite the padding and gap by setting styles on `<calcite-action-grid>`, but in Calcite 1.7.0, the grid is now applied on a shadow DOM element, rather than on the host element (ever since commit https://github.com/Esri/calcite-design-system/commit/b34f36d53b80011e7e946cfe30d1d85d3857d12a @driskull)

Thus, after Calcite update, I am not able to overwrite these styles without going into shadow dom, which broke my UI:

(before update on the left; after update on the right)

![New Project](https://github.com/Esri/calcite-design-system/assets/40512816/4c01c045-4f3a-49bf-b60e-d63cde932d82)

Can you please either remove padding, or add a CSS variable to customize it?
I would appreciate the removal/customization of gap too, but that is a bit less critical as I can change grid background to mask it (though, there would still be a small issue of a 1px unclickable areas between buttons, which could lead to bad UX for a tacktile widget like a D-pad)

(this is needed before the next JS SDK release a month from now)

**Comment by jcfranco** [comment]
As a workaround, could you override the background-color of the action-pad to at least make the grid spacing less apparent (see https://codepen.io/jcfranco/pen/MWZePdb?editors=1000)?

**Comment by maxxxxxdlp** [comment]
yes, that's why I mentioned:

> but that is a bit less critical as I can change grid background to mask it

and the consequence:

> though, there would still be a small issue of a 1px unclickable areas between buttons, which could lead to bad UX for a tacktile widget like a D-pad

but again, the padding:1px is a larger issue

**Comment by jcfranco** [comment]
> but that is a bit less critical as I can change grid background to mask it

Whoops. Sorry I missed that. 😅

@macandcheese Is there an existing CSS prop we could add to `action-pad` for this?

**Comment by driskull** [comment]
I think we would need to introduce a css var on the `action-group` for this.

**Comment by geospatialem** [comment]
Verified in `1.9.0-next.5` with the `--calcite-action-group-gap` and `--calcite-action-group-padding` css variables (when the Action Group's `layout` is set to `"grid"`:

```css
  calcite-action-group {
    --calcite-action-group-gap: 0;
    --calcite-action-group-padding: 0;
  }
```
