### ISSUE TITLE
[Calcite Date Picker] Year value adds leading zeros when two numbers are added to the component

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7588]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Filed as Online bug: `BUG-000159719`.

When a user types in a date with two digits for the year the year is provided a value with two leading zeros. 

For instance: `8/1/23` > `0023-08-01`

Came up in the efforts of https://github.com/Esri/calcite-design-system/issues/3526, but is a separate bug. Sectioning out for clarity and prioritization. 

cc: @banuelosj @amring1

### Expected Behavior

Not sure if we should automatically add in the first two numerical values, but at a minimum the value shouldn't register since its invalid. Perhaps in this case the value remains as `""`? cc: @jcfranco 

### Reproduction Sample

https://codepen.io/banuelosj/pen/qBQyNrQ

### Reproduction Steps

1. Open https://codepen.io/banuelosj/pen/qBQyNrQ
2. Type a date with the year ending in two digits, for instance 8/1/23
3. Select outside the date to close the component
4. Observe the date is displayed as `0023-08-01`

### Reproduction Version

1.4.3

### Priority impact

p1 - need for current milestone

### Impact

Should be mitigated ASAP for inclusion in the upcoming R3 releases.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by anveshmekala** [comment]
Regarding expected behavior, native input of type="date" does allow users to type dates before the specified `min` and return them on `change` event.  If we consider the example [here ]( min="2023-08-01") , the change event target value is formatted similar to `calcite-date-picker` one. The difference in behavior is related to the format we display in the input field rather than the target value ( 8/1/23 vs 08/01/0023). Since validation effort is handled in https://github.com/Esri/calcite-design-system/issues/4276, we can utilize this to display right format `08/01/0023` in the input field.


Thoughts? @geospatialem @jcfranco

**Comment by jcfranco** [comment]
@anveshmekala I like the idea of normalizing the value when the input is blurred or when the date is modified via the calendar, but I think this is slightly different. 

The observed behavior is technically working as expected albeit not very useful to users. 🤓 As a convenience, we could normalize any 2-digit year values to follow the latest century ([example](https://codepen.io/jcfranco/pen/GRPozKw?editors=1111)).

**Comment by geospatialem** [comment]
Verified in `1.7.0-next.17`
![verify-7588](https://github.com/Esri/calcite-design-system/assets/5023024/af2ca698-3585-41ce-af3a-dd439bbd3fe1)
