### ISSUE TITLE
Combobox: update chevron colors

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7711]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Combobox's chevrons are `ui-text-1` in all states.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/7e34831b-fcaa-48e1-9689-0e4ac53f99e2)

### Expected Behavior

For system consistency, chevrons should be `ui-text-3` when idle and `ui-text-1` when hovered or pressed.

![image](https://github.com/Esri/calcite-design-system/assets/5023024/012d0164-0c7c-489e-aaff-7c2cafbddab7)

### Reproduction Sample

https://codepen.io/ashetland/pen/MWZpgRd

### Reproduction Steps

Interact with Combobox.

### Reproduction Version

v1.8.0

### Relevant Info

Figma designs for Combobox [here](https://www.figma.com/file/d7UBycO6x1Vz8zskFj5dTI/Epic---icon-consistency-%5B7181%5D?type=design&node-id=914-348742&mode=dev).

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Web Analysis

**Comment by brittneytewks** [comment]
Removed Figma changes label as this will be tracked in monday.com

**Comment by DitwanP** [comment]
When the `combobox` is expanded, the color of the chevron is not `ui-text-3` except for the split second when you press on an option. You can hold the mouse down on an option to see the color change. It looks like its because it's in a focused state and not really "idle". In the pen below you can see what I'm talking about, the `input-time-picker` works because it's not actually focused after press, and I'm not sure about `select` because it's covered by options when expanded 

@ashetland Thoughts on this? Depending on what you think I might have to reopen the issue for date picker chevron colors as well. 

@aPreciado88 for 👀

https://codepen.io/Ditwan-Price/pen/JjVzKWp?editors=1000

**Comment by ashetland** [comment]
Nice catch! I think this may just be an issue with Combobox because two things are focused at the same time. I'd consider this dual focus to be a bug, fwiw.

**Comment by aPreciado88** [comment]
@DitwanP @ashetland I confirmed with @jcfranco that the double focus is intentional. I can update the chevron's color to always be `ui-text-3` like Aaron suggested. Or I can change it to only be `ui-text-1` when the combobox is being hovered or clicked. Please let me know which option you like better.

**Comment by ashetland** [comment]
That might be a better compromise, @aPreciado88. I like that at least the hover state would match across components even if the focus state is slightly off on Combobox. Let's try it!

**Comment by aPreciado88** [comment]
@ashetland The changes are up!

**Comment by ashetland** [comment]
Looks good!

**Comment by DitwanP** [comment]
🍠 Verified on `2.8.0-next.14`
