### ISSUE TITLE
calcite-tile with action and tooltip

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-design-system#7905]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Calcite tile should be able to accept an action with a tooltip in the content-end slot.

![image](https://github.com/Esri/calcite-design-system/assets/44481292/543c2a7d-1e76-4ec8-a440-948c01854fae)

Tooltip currently doesn't show when hovering over action
https://codepen.io/afreitag/pen/poqKaZV

Currently a tooltip can only be set on the entire tile

![image](https://github.com/Esri/calcite-design-system/assets/44481292/a1e8d6cf-4d56-4c45-80f3-f4493702c360)

### Acceptance Criteria

tooltip shows when hovering over launch action

### Which Component

calcite-tile

### Example Use Case

Map Viewer layer information section

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

**Comment by macandcheese** [comment]
Tiles are wholly interactive entities with a single hitbox, this is a distinguishing feature of the component. 

In the above screenshot, it’s accurate to have the tooltip show on the entire action. Not sure we want to split Tile into multiple hit boxes / have action slots.

I do wonder how useful the tooltip is in this scenario, or if it could be integrated into the card if that text is absolutely needed. Otherwise, I’d say it’s functioning as expected, since the tooltip applies to the entire action. 

You could try to use a Card, or a single List / List Item, etc if you don’t want an entire clickable component.

**Comment by AdelheidF** [comment]
cc @mitc7862 @cwwhitmore

**Comment by driskull** [comment]
Yeah I agree with what @macandcheese said.

The alternative would be to possibly use a notice component.

**Comment by geospatialem** [comment]
Closing out the above to use alternative components mentioned in https://github.com/Esri/calcite-design-system/issues/7905#issuecomment-1741165593 and https://github.com/Esri/calcite-design-system/issues/7905#issuecomment-1741519495.
