### ISSUE TITLE
Reduce numbering system allow list to officially supported ones

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#8216]
### Description

We are officially supporting `arab`, `arabext`, and `latn` as numbering systems, so we need to make this clear in the code and documentation. 

cc @annierm18 @eriklharper

### Proposed Advantages

Clearer story regarding supported numbering systems. 

### Which Component

This would impact all components supporting a `numberingSystem` prop.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by jcfranco** [comment]
+@macandcheese @geospatialem for doc and doc-site considerations.

**Comment by benelan** [comment]
> +@macandcheese @geospatialem for doc and doc-site considerations.

++ @DitwanP

Can we add the new list of supported numbering systems to [this section](https://developers.arcgis.com/calcite-design-system/resources/localization/#numbering-system), since we already list the `lang`s above it?

We should probably also remove the part saying to check MDN for a list of available numbering systems. But I think we should still link to MDN for the "more info".

The list of numbering systems in the prop doc will automatically be updated since it comes from the source code. 

Thanks!

**Comment by eriklharper** [comment]
> A numbering system conveys numbers using digits or symbols in a consistent format, as defined by the set lang.

I think we should revise this sentence in the docs as well.  Technically the lang doesn't define the numbering-system since its a separate property and we're not forcing `ar` to use the `arab` numbering-system, for example.

**Comment by eriklharper** [comment]
It would be cool to add `arab` and `arabext` as supported numbering systems next to or maybe as a sub-bullet below the applicable lang/locale, so in this case `Arabic (ar)`.  I think we should go so far as to say _"only specific combinations of lang and numbering-system are supported, and here's what they are"._  Same goes for the`thai` numbering system with the `Thai (th)` locale.
