### ISSUE TITLE
Programmatically setting `calcite-select`'s `value` property should fire `calciteSelectChange`

### ISSUE THREAD

**Issue by COV-GIS** [Esri/calcite-design-system#8927]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As stated in title.

### Acceptance Criteria

If the `value` is set programmatically the correct option is selected and `selectedOption` updates. So `calciteSelectChange` should fire.

### Relevant Info

https://codepen.io/COV-GIS/pen/PogzObZ

### Which Component

select

### Priority impact

p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by jcfranco** [comment]
Would you mind sharing more about your use case? 

We intentionally don't emit the change event when setting the value programmatically on `calcite-select` (see  https://github.com/Esri/calcite-design-system/issues/2125 and https://github.com/Esri/calcite-design-system/issues/2033).

This behavior also aligns with native form controls:

* [select](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element:send-select-update-notifications:~:text=Upon%20such%20an%20element,attribute%20initialized%20to%20true.) ([toy example](https://codepen.io/jcfranco/pen/gOygqNj?editors=1111))
* [input](https://html.spec.whatwg.org/multipage/input.html#common-input-element-events)

You should be able to run change-related logic when setting the value directly instead of depending on the change event.
