### ISSUE TITLE
[input time zone] Update and re-organize timezone dropdown options for improved usability

### ISSUE THREAD

**Issue by emmilaakso212** [Esri/calcite-design-system#9018]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

As a user who wants to select a time zone using the time zone picker, I want to be able to easily identify which time zone is relevant to me. 

### Acceptance Criteria

Replace "name" mode of the time zone picker with a new version, or create this as a third version, if needed.

**Content:**

Add the following data to timezone options:
- Country, unless the name of the country is the name of the timezone
- State or province, if there is more than one timezone in the country. Countries that have more than one timezone.
- Always show offset in UTC (https://github.com/Esri/calcite-design-system/issues/8716)

**Content order:**

- Show dropdown items in format of city, state/province*, country* [UTC-offset]
- Group timezone data by continent, and show continent name once as a group label
- Organize dropdown results alphabetically by city name (some timezones/offsets will appear more than once. That’s ok)

*optional content

**UI/behavior**

- If timezone picker had an existing value, by default scroll in the results such that the previous value is at the top
- Allow searching within the options by city, state or province, country, or offset

[See Figma for designs](https://www.figma.com/file/JXlrtCx8WmsXZRk8Lzd9Oq/Timezone%2Ftime-based-filters?type=design&node-id=244%3A170564&mode=dev&t=sZtk9aueJq3GU4xz-1)

### Relevant Info

Agreed upon enhancement work for Map Viewer team for implementation by 24-R3

### Which Component

Time zone picker

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Map Viewer

### Related issues

- https://github.com/Esri/calcite-design-system/issues/8716
- https://github.com/Esri/calcite-design-system/issues/9026

**Comment by emmilaakso212** [comment]
cc: @jcfranco

**Comment by geospatialem** [comment]
Aiming for dev implementation prior to R3 based on Online priorities - currently targeted for May. cc @emmilaakso212

**Comment by AdelheidF** [comment]
I guess this won't make it for Online release R2 then, unfortunately.

**Comment by jcfranco** [comment]
Belated update on this one, the following enhancements to combobox have been addressed this release to match the proposed design spec:

* #8716 
* #9026/#7212 

The following are adjustments to the original requirements (per conversation w/ @emmilaakso212  and @ashetland):

1. Country and city will be the only additions for now.
1. Options will be grouped by IANA region and not continent per se.
1. Time zones should not be duplicated due to DST as this new mode will be primarily geographically-driven (searching by region, continent, country, etc.).
1. The dropdown already displays the selected value when opened, so no adjustments needed.
1. We'll consider using the exiting Intl offset format vs using decimal format. 
1. Offset can be displayed as is (i.e., no need to change from `()` to `[]`) since it will be displayed differently once https://github.com/Esri/calcite-design-system/issues/3695 lands.
1. We'll consider changing the `offsetStyle` default in a breaking change release. For now, internal apps need to opt into using UTC.

The grouping and additional metadata for improved search UX will be tackled in the July release.

**Comment by jcfranco** [comment]
FWIW, this got pushed to August for additional testing, but here's a preview: https://codepen.io/jcfranco/pen/rNEjyQJ. It should be available via `@next` sometime this week.

**Comment by AdelheidF** [comment]
Does this include an update to the messages_xx.json files to also include some type of region information so we can have a unified format/way of displaying the current time zone in various components?

<img src=https://github.com/user-attachments/assets/d4c01b3f-6d81-4983-b48a-4652798be401 width=250/>

![image](https://github.com/user-attachments/assets/8969c885-4478-42f2-9cba-b8e517284e4e)

**Comment by jcfranco** [comment]
Do you mean metadata behind each time zone option? If so, that wasn't a part of the original request. In the new mode, the time zone options are grouped by region using `timezone-groups` behind the scenes.

FWIW, [`timezone-groups`](https://github.com/jcfranco/timezone-groups/issues) will have some enhancements coming up soon to provide additional utils for this.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.4`

**Comment by DitwanP** [comment]
Sorry @jcfranco I missed something here, did we still want to make it so the selected value is shown at the top of the dropdown when it opens? As it is now I see it at the bottom:
![image](https://github.com/user-attachments/assets/e7675392-30dc-4268-9659-e57c9f97c75c)

I'm referring to this btw:
"If timezone picker had an existing value, by default scroll in the results such that the previous value is at the top"

**Comment by jcfranco** [comment]
This is expected. We revised this after meeting w/ @emmilaakso212 and @ashetland. From [an earlier comment](https://github.com/Esri/calcite-design-system/issues/9018#issuecomment-2187957056):

> 4. The dropdown already displays the selected value when opened, so no adjustments needed.
