### ISSUE TITLE
Date selected in input-date-picker gets cleared for "bs", "it-CH" locales

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-design-system#9387]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The selected date gets cleared (and is replaced by the placeholder) when the user clicks out of the component for the "bs", "it-CH" locales.

### Expected Behavior

- [ ] The selected date would remain, like it does for the "en" locale
- [ ] Add test coverage for future support

### Reproduction Sample

https://codepen.io/annierm18/pen/YzbqdXO?editors=100

### Reproduction Steps

1. Open input-date-picker in codepen
2. Add the lang="bs" or "it-CH" tag
3. Select a date from the calendar
4. Click outside of the component

### Reproduction Version

2.8.2

### Relevant Info

There is a corresponding dev issue for this: https://devtopia.esri.com/WebGIS/arcgis-enterprise-manager/issues/1758. It says "The issue is reproducible on Chrome and Edge Chromium"

This next line is only being put here in order to verify an automation, ignore it.
Blocked issues: #9722

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Enterprise

**Comment by geospatialem** [comment]
Added the `p - high` label as suggested by @annierm18 and the i18n team.

**Comment by Akochure** [comment]
Thanks, @annierm18, for logging the issue. We have used the temporary fix based on Blake's comment - https://github.com/Esri/calcite-design-system/issues/4583#issuecomment-1156807166. But need to fix this issue in the component.

**Comment by anveshmekala** [comment]
Did some digging and this is expected for few locales since we are relying `toLocaleDateString` API which is implementation specific.  Safari and firefox handles `bs` locale as expected but not `chrome`.  `it-CH` locale has reported issue in CLDR https://unicode-org.atlassian.net/browse/CLDR-16491 for date separator.

Quick workaround would be to fallback to `bs-Cyrl` for `bs` locale and `de-CH` locale for `it-CH` for the string conversion part. 

Using `toLocaleDateString` as source of truth for string conversion of locale specific dates  going forward needs to be reviewed .

**Comment by driskull** [comment]
Related issues:

https://issues.chromium.org/issues/40172622

toLocaleDateString also says this on MDN.

> very time toLocaleString is called, it has to perform a search in a big database of localization strings, which is potentially inefficient. When the method is called many times with the same arguments, it is better to create a [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) object and use its [format()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/format) method, because a DateTimeFormat object remembers the arguments passed to it and may decide to cache a slice of the database, so future format calls can search for localization strings within a more constrained context.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by driskull** [comment]
> Using toLocaleDateString as source of truth for string conversion of locale specific dates going forward needs to be reviewed .

Agreed.

It seems like date formatting to locales is unreliable and inconsistent. Trying to format to a single string and parse a single string to day, month, year is complex because of these inconsistencies.

We may want to break up the single input into three separate inputs like we have for time-picker. Then we don't have to worry about parsing a single string, separator issues and intl bugs.

> Quick workaround would be to fallback to bs-Cyrl for bs locale and de-CH locale for it-CH for the string conversion part.

I think we should do this for now.

**Comment by DitwanP** [comment]
🍡 Verified on `2.12.0-next.9`
https://codepen.io/Ditwan-Price/pen/bGPoGwp?editors=100

**Comment by driskull** [comment]
Needs re-verification.

**Comment by geospatialem** [comment]
> Needs re-verification.

Verified in `2.12.0-next.32` 🎉
