### ISSUE TITLE
performance issue with floating-ui-owning components

### ISSUE THREAD

**Issue by ycabon** [Esri/calcite-design-system#9397]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Creating many `calcite-action-menu` takes a lot of time due to the wiring of DOM events for the floating menu.

The function `connectFloatingUI` is called many times even when the floating menu is not visible.
![image](https://github.com/Esri/calcite-design-system/assets/1074239/08d76b2f-759b-495d-a45c-b52bff86933a)

### Expected Behavior

Delay wiring events until the button is clicked.

### Reproduction Sample

https://codepen.io/ycabon/pen/gOJrZNa?editors=1010

### Reproduction Steps

1. open Devtools, on the performance tab.
2. start profiling
3. click on the button "Create LayerList"
4. stop profiling

### Reproduction Version

2.8.1

### Priority impact

impact - p1 - need for current milestone

### Impact

Impacts the JS SDK `LayerList` component when working with maps with many layers and actions defined on each item of the list.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Maps SDK for JavaScript

**Comment by jcfranco** [comment]
Looked at this earlier w/ @ycabon and this affects all `FloatingUIComponent` implementors. Updated title to reflect this.

**Comment by driskull** [comment]
The `action-menu` component uses the `calcite-popover` internally.

In the popover, `connectFloatingUI` is called in 3 different scenarios:

- connectedCallback: when a component is added or moved within the DOM. 
- componentDidLoad: once the component is loaded. // We might be able to remove this one 
- referenceElement: when a referenceElement is added or changed.

> Delay wiring events until the button is clicked.

@jcfranco In order to avoid flashing open in one area and then moving to another after floating-ui positions correctly, we may need to add some sort of an internal state to each component to know once floating-ui has returned a position.

After `autoUpdate`, instead of just calling `reposition()`. we can enhance the `FloatingUIComponent` and add a callback that we can call after `autoUpdate` where we can let the component know it has a position. Then we can display the component after it has a `referenceElement`, `postion` and  is `open`.

**Comment by jcfranco** [comment]
Thanks for the info and suggestion, @driskull! I'll take that into consideration.

**Comment by DitwanP** [comment]
🍭 Verified, the time it takes to generate the list seems shorter as well as the profiler seems to indicate that there's less work being done.

**Comment by ycabon** [comment]
Thanks for the fix, it looks great!
