### ISSUE TITLE
Combobox: When you tab into the input, the options do not appear

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/calcite-design-system#9401]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Tabbing into the input causes the dropdown options to not appear, even when you start typing. This does not match the behavior after you click into the input.

### Expected Behavior

I would expect to be able to see the filtered results whether I click on the combobox or tab into it.

### Reproduction Sample

https://developers.arcgis.com/calcite-design-system/components/combobox/

### Reproduction Steps

1. Tab into the combobox input.
4. Start typing. You will not see the dropdown with matching options appear no matter what you type.
5. Once you click on the the combobox, the options will start appearing.

### Reproduction Version

2.8.2

### Relevant Info

Tested in Chrome and Firefox.

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [X] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

ArcGIS Developer Experience

**Comment by jcfranco** [comment]
We should definitely display any matched options when typing after tabbing into the component.

Not opening on focus is by design. This approach adheres to [WAI-ARIA combobox guidance](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboard_interaction) and is consistent with similar components (e.g., input-date-picker, input-time-picker). cc @geospatialem

**Comment by DitwanP** [comment]
🥭 Verified locally on `dev`
