### ISSUE TITLE
[Dialog] When `overlay-position="fixed"` and `menu-open` is present the menu is not positioned as-expected

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9876]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `overlay-position="fixed"` and `menu-open` is present the menu is not positioned as-expected: 
![image](https://github.com/user-attachments/assets/67a4c677-d10e-45e2-9ab4-8f773d1848a4)

### Expected Behavior

The menu should be placed as-expected on the component (where it is initially loaded):

![image](https://github.com/user-attachments/assets/adacdd7e-0f5b-4076-b35f-9b0154a70bbc)

### Reproduction Sample

https://codepen.io/geospatialem/pen/ZEdLWNZ

### Reproduction Steps

1. Open the [sample](https://codepen.io/geospatialem/pen/ZEdLWNZ)
2. Observe the menu opens as-expected
3. However, it is repositioned in a different location

### Reproduction Version

`2.11.0-next.25`

### Relevant Info

Spurred from https://github.com/Esri/calcite-design-system/issues/7886 QA/QC

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (dev)

**Comment by driskull** [comment]
This appears to be a an issue with the `transform` animation on the dialog. If we remove that, it works fine.

The issue is that having a transform animation with a floating-ui element inside of it can cause positioning issues.

Some notes about it can be read here: https://floating-ui.com/docs/usefloating#transform

In our case, a wrapper won't work because the floating ui element is inside of the transform animation.

As a workaround, I could disable the animation if the `menu-open` attribute is present. WDYT @jcfranco?

**Comment by DitwanP** [comment]
🍡 Verified locally on `dev`
